export { default as AdvanceTab } from './AdvanceTab.vue'
export { default as AppHeader } from './AppHeader.vue'
export { default as EventsTab } from './EventsTab.vue'
export { default as LeftMenu } from './LeftMenu.vue'
export { default as PropsTab } from './PropsTab.vue'
export { default as RightPanel } from './RightPanel.vue'
export { default as StylesTab } from './StylesTab.vue'
export { default as ViewContent } from './ViewContent.vue'
