import { ref, markRaw } from 'vue'
import {
  PhImage,
  PhTextH,
  PhTextT,
  PhSquare,
  PhChat,
  PhDresser,
  PhListChecks,
  PhTable,
  PhGridNine,
  PhTreeStructure,
  PhFunnel,
  PhElevator,
  PhArticle,
  PhLadderSimple,
  PhChartBar,
  PhChartPie,
  PhChartDonut,
  PhChartLine,
  PhCube,
  PhSquareHalfBottom,
  PhRadioButton,
  PhLineVertical,
  PhGlobeHemisphereEast,
  PhLinkSimpleHorizontalBreak,
  PhLink,
  PhBread,
  PhSteps,
  PhFiles,
  PhCheckSquare,
  PhChecks,
  PhCalendar,
  PhCalendarMinus,
  PhTextbox,
  PhFile,
  PhMagnifyingGlass,
  PhToggleLeft,
  PhArticleNyTimes,
  PhUpload,
  PhUserCircle,
  PhSlideshow,
  PhMonitorPlay,
  PhLineSegment,
  PhTree,
  PhCornersOut,
  PhSquareSplitVertical,
  PhCards,
  PhQuestion,
  PhChatCircleDots,
  PhSpinner,
  PhPuzzlePiece,
  PhSticker,
  PhPassword,
  PhSquareSplitHorizontal,
} from '@phosphor-icons/vue'
const icons = {
  image: markRaw(PhImage),
  text: markRaw(PhTextH),
  textT: markRaw(PhTextT),
  square: markRaw(PhSquare),
  chat: markRaw(PhChat),
  dresser: markRaw(PhDresser),
  listChecks: markRaw(PhListChecks),
  table: markRaw(PhTable),
  grid: markRaw(PhGridNine),
  tree: markRaw(PhTreeStructure),
  funnel: markRaw(PhFunnel),
  elevator: markRaw(PhElevator),
  article: markRaw(PhArticle),
  simple: markRaw(PhLadderSimple),
  bar: markRaw(PhChartBar),
  pie: markRaw(PhChartPie),
  donut: markRaw(PhChartDonut),
  line: markRaw(PhChartLine),
  cube: markRaw(PhCube),
  bottom: markRaw(PhSquareHalfBottom),
  button: markRaw(PhRadioButton),
  lineV: markRaw(PhLineVertical),
  east: markRaw(PhGlobeHemisphereEast),
  hbreak: markRaw(PhLinkSimpleHorizontalBreak),
  link: markRaw(PhLink),
  bread: markRaw(PhBread),
  steps: markRaw(PhSteps),
  files: markRaw(PhFiles),
  check: markRaw(PhCheckSquare),
  checks: markRaw(PhChecks),
  date: markRaw(PhCalendar),
  dateRange: markRaw(PhCalendarMinus),
  input: markRaw(PhTextbox),
  file: markRaw(PhFile),
  search: markRaw(PhMagnifyingGlass),
  switch: markRaw(PhToggleLeft),
  times: markRaw(PhArticleNyTimes),
  upload: markRaw(PhUpload),
  avatar: markRaw(PhUserCircle),
  slide: markRaw(PhSlideshow),
  vedio: markRaw(PhMonitorPlay),
  lineS: markRaw(PhLineSegment),
  treeS: markRaw(PhTree),
  corner: markRaw(PhCornersOut),
  split: markRaw(PhSquareSplitVertical),
  cards: markRaw(PhCards),
  ask: markRaw(PhQuestion),
  dots: markRaw(PhChatCircleDots),
  spinner: markRaw(PhSpinner),
  custom: markRaw(PhPuzzlePiece),
  sticker: markRaw(PhSticker),
  password: markRaw(PhPassword),
  splitH: markRaw(PhSquareSplitHorizontal),
}
const tabs = ref([
  { id: 'advance', name: '精选组件' },
  { id: 'unit', name: '原子组件' },
  { id: 'custom', name: '低代码组件' },
])
const comGroup = ref([
  {
    id: 'advance',
    name: '精选组件',
    children: [
      {
        name: '基础元素',
        open: true,
        show: true,
        children: [
          { name: '图片', show: true, type: '', icon: icons.image },
          { name: '标题', show: true, type: '', icon: icons.text },
          { name: '正文', show: true, type: '', icon: icons.textT },
        ],
      },
      {
        name: '布局容器类',
        open: true,
        show: true,
        children: [
          { name: '自然布局', show: true, type: '', icon: icons.square },
          { name: '容器', show: true, type: 'Container', icon: icons.square },
          { name: '自由节点', show: true, type: '', icon: icons.square },
          { name: '页头', show: true, type: '', icon: icons.square },
          { name: '高级对话框', show: true, type: '', icon: icons.chat },
          { name: '高级抽屉', show: true, type: '', icon: icons.dresser },
          { name: '选项卡', show: true, type: '', icon: icons.listChecks },
        ],
      },
      {
        name: '表格类',
        open: true,
        show: true,
        children: [
          { name: '可编辑表格', show: true, type: '', icon: icons.table },
          { name: '母子表格', show: true, type: '', icon: icons.table },
          { name: '查询筛选', show: true, type: '', icon: icons.funnel },
          { name: '分组表格', show: true, type: '', icon: icons.grid },
          { name: '高级表格', show: true, type: '', icon: icons.table },
          { name: '树状表格', show: true, type: '', icon: icons.tree },
        ],
      },
      {
        name: '表单类',
        open: true,
        show: true,
        children: [
          { name: '电梯表单', show: true, type: 'EvelatorForm', icon: icons.elevator },
          { name: '高级表单', show: true, type: 'Form', icon: icons.article },
          { name: '步骤表单', show: true, type: '', icon: icons.simple },
        ],
      },
      {
        name: '图表',
        open: true,
        show: true,
        children: [
          { name: '面积图', show: true, type: '', icon: icons.pie },
          { name: '条形图', show: true, type: '', icon: icons.bar },
          { name: '柱状图', show: true, type: '', icon: icons.bar },
          { name: '环形图', show: true, type: '', icon: icons.donut },
          { name: '折线图', show: true, type: '', icon: icons.line },
          { name: '饼图', show: true, type: '', icon: icons.pie },
        ],
      },
    ],
  },
  {
    id: 'unit',
    name: '原子组件',
    children: [
      {
        name: '布局容器类',
        open: true,
        show: true,
        children: [
          { name: 'Box', show: true, type: '', icon: icons.cube },
          { name: '对话框', show: true, type: '', icon: icons.chat },
          { name: '隐藏底部', show: true, type: '', icon: icons.bottom },
          { name: '侧抽屉', show: true, type: '', icon: icons.dresser },
          { name: '底部抽屉', show: true, type: '', icon: icons.dresser },
        ],
      },
      {
        name: '通用',
        open: true,
        show: true,
        children: [
          { name: '按钮', show: true, type: '', icon: icons.hbreak },
          { name: '分隔按钮', show: true, type: '', icon: icons.hbreak },
          { name: '菜单按钮', show: true, type: '', icon: icons.hbreak },
          { name: '按钮组', show: true, type: '', icon: icons.hbreak },
          { name: '分隔线', show: true, type: '', icon: icons.lineV },
          { name: '图标', show: true, type: '', icon: icons.east },
          { name: '链接', show: true, type: '', icon: icons.link },
        ],
      },
      {
        name: '引导',
        open: true,
        show: true,
        children: [
          { name: '面包屑', show: true, type: '', icon: icons.bread },
          { name: '翻页器', show: true, type: '', icon: icons.files },
          { name: '步骤', show: true, type: '', icon: icons.steps },
        ],
      },
      {
        name: '信息输入',
        open: true,
        show: true,
        children: [
          { name: '普通型', show: true, type: 'Text', icon: icons.input },
          { name: '自定义', show: true, type: '', icon: icons.custom },
          { name: '级联选择器', show: true, type: '', icon: icons.listChecks },
          { name: '级联', show: true, type: '', icon: icons.listChecks },
          { name: '复选按钮', show: true, type: 'SCheckbox', icon: icons.check },
          { name: '复选按钮组', show: true, type: 'CheckboxGroup', icon: icons.checks },
          { name: '日期选择框', show: true, type: 'Date', icon: icons.date },
          { name: '日期区间', show: true, type: 'DateRange', icon: icons.dateRange },
          { name: '表单容器', show: true, type: '', icon: icons.file },
          { name: '输入框', show: true, type: 'Text', icon: icons.input },
          { name: '密码框', show: true, type: '', icon: icons.password },
          { name: 'TextArea', show: true, type: 'TextArea', icon: icons.input },
          { name: 'NextTable', show: true, type: '', icon: icons.table },
          { name: '数字输入框', show: true, type: 'Number', icon: icons.input },
          { name: '单选按钮', show: true, type: 'Radio', icon: icons.button },
          { name: '单选按钮组', show: true, type: 'RadioGroup', icon: icons.button },
          { name: '区段选择器', show: true, type: '', icon: icons.input },
          { name: '搜索', show: true, type: '', icon: icons.search },
          { name: '带分类', show: true, type: '', icon: icons.input },
          { name: '选择器', show: true, type: '', icon: icons.input },
          { name: '开关组件', show: true, type: 'Switch', icon: icons.switch },
          { name: '时间选择框', show: true, type: '', icon: icons.times },
          { name: '穿梭框', show: true, type: '', icon: icons.splitH },
          { name: '树型选择控件', show: true, type: '', icon: icons.tree },
          { name: '上传组件', show: true, type: '', icon: icons.upload },
        ],
      },
      {
        name: '信息展示',
        open: true,
        show: true,
        children: [
          { name: '头像', show: true, type: '', icon: icons.avatar },
          { name: '徽标数', show: true, type: '', icon: icons.avatar },
          { name: '卡片型', show: true, type: '', icon: icons.cards },
          { name: '面板型', show: true, type: '', icon: icons.splitH },
          { name: '全屏型', show: true, type: '', icon: icons.corner },
          { name: '图片轮播', show: true, type: '', icon: icons.slide },
          { name: '标签', show: true, type: '', icon: icons.sticker },
          { name: '可关闭标签', show: true, type: '', icon: icons.sticker },
          { name: '可选中标签', show: true, type: '', icon: icons.sticker },
          { name: '时间轴', show: true, type: '', icon: icons.lineS },
          { name: '树型控件', show: true, type: '', icon: icons.treeS },
          { name: '视频', show: true, type: '', icon: icons.vedio },
        ],
      },
      {
        name: '信息反馈',
        open: true,
        show: true,
        children: [
          { name: '提示', show: true, type: '', icon: icons.ask },
          { name: '气泡框', show: true, type: '', icon: icons.chat },
          { name: '加载', show: true, type: '', icon: icons.spinner },
          { name: '进度指示器', show: true, type: '', icon: icons.spinner },
          { name: '面包片', show: true, type: '', icon: icons.bread },
        ],
      },
    ],
  },
  {
    id: 'custom',
    name: '低代码组件',
    children: [
      {
        name: '低代码组件',
        open: true,
        show: true,
        children: [{ name: '低代码组件', show: true, type: '', icon: icons.custom }],
      },
    ],
  },
])
export default { tabs, comGroup }
