import { ComponentProps } from '@/domain/schema'
export const COMPONENT_NAME_MAPPING = {
  Image: '图片',
  Static: '自然布局',
  Container: '容器',
  Dialog: '高级对话框',
  Tabs: '选项卡',
  EditTable: '可编辑表格',
  ParentTable: '母子表格',
  Filter: '查询筛选',
  GroupTable: '分组表格',
  EvelatorForm: '电梯表单',
  Form: '高级表单',
  StepForm: '步骤表单',
  Pie: '饼图',
  Square: '条形图',
  Circle: '环形图',
  Line: '折线图',
  Ask: '对话框',
  Button: '按钮',
  SplitButton: '分隔按钮',
  MenuButton: '菜单按钮',
  ButtonGroup: '按钮组',
  SplitLine: '分隔线',
  Icon: '图标',
  Link: '链接',
  Text: '输入框',
  TextArea: 'TextArea',
  Number: '数字输入框',
  Password: '密码框',
  Date: '日期选择框',
  DateRange: '日期区间',
  Radio: '单选按钮',
  RadioGroup: '单选按钮组',
  SCheckbox: '复选按钮',
  CheckboxGroup: '复选按钮组',
  Address: '地址级联',
  Switch: '开关组件',
  Search: '搜索',
  CategorySearch: '分类搜索',
  Upload: '上传组件',
  Custom: '低代码组件',
}
export const COMPONENT_DEFAULT_PROPS: ComponentProps = {
  cid: '',
  parent: '',
  name: '',
  col: 2,
  label: '标签标题',
  errTip: '',
  helpTip: '',
  validateStatus: 1,
  size: 1,
  tip: false,
  device: 2,
  require: false,
  preview: false,
  autoValidate: false,

  defaultVal: '',
  placeholder: '',
  maxLength: Infinity,
  clear: false,
  disable: false,
  readonly: false,
  hover: false,
  trim: true,
  border: true,
  focus: false,
  showIcon: false,

  tabStatus: 1,
  tabLayout: 2,
  labelPos: 'left',
  labelAlign: 0,

  isContainer: false,
  parentDirect: 'column',

  inlineStyle: {},
}
